"""empty message

Revision ID: ce68ecdb4c03
Revises: ca866253ef3b
Create Date: 2019-11-29 16:55:34.146956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce68ecdb4c03'
down_revision = 'ca866253ef3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=360), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.execute('Update "Venue" SET seeking_talent = False WHERE seeking_talent IS NULL;')
    op.alter_column('Venue','seeking_talent', nullable=False)
    # ### end Alembic commands ###   

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description', nullable = False)
    # ### end Alembic commands ###
